### PR TITLE
Update custom elements

### PR DESCRIPTION
**Pull request by Mihaiii**
For Starcounter/RebelsLounge#193

### CODE REVIEW

**Comment by Mihaiii** [comment]
The latest commit consists in a update of `bower.json` - all dependencies would use latest version in case there would be no conflicts.
But at `bower update` I get `ECONFLICT Unable to find suitable version for paper-input`. Therefore, at this moment, I don't think that a merge should contain the latest commit.

**Comment by Mihaiii** [comment]
@habib535 Please see if you could find a [hybrid element](https://www.polymer-project.org/2.0/docs/devguide/hybrid-elements) (Polymer version 1.9 - 2) that could replace `PolymerEl/paper-tags`.

We are migrating to Polymer 2 and this element is not compatible with it.

**Comment by warpech** [comment]
@habib535, any updates on this?

`PolymerEl/paper-tags` makes the situation really poor, because I cannot do a clean `bower install` because of lots of errors. To suppress the error, I needed to add a wall of resolutions to `bower.json`:

Other than that, most of the custom elements are out of date in this PR. See `bower list`:

```
│ │ ├── iron-a11y-keys-behavior#1.1.9 (latest is 2.0.1)
│ │ ├─┬ iron-selector#1.5.3 (latest is 2.0.0)
│ ├─┬ iron-flex-layout#1.3.7 (latest is 2.0.0)
│ ├─┬ iron-icon#1.0.13 (latest is 2.0.1)
│ │ ├── iron-flex-layout#1.3.7 (latest is 2.0.0)
│ │ ├─┬ iron-meta#1.1.3 (latest is 2.0.2)
│ ├─┬ iron-iconset-svg#1.1.2 (latest is 2.1.0)
│ ├─┬ iron-input#1.0.11 (latest is 2.0.1)
│ │ ├─┬ iron-a11y-announcer#1.0.6 (latest is 2.0.0)
│ │ ├─┬ iron-validatable-behavior#1.1.2 (latest is 2.0.0)
│ ├─┬ iron-resizable-behavior#1.0.6 (latest is 2.0.1)
│ ├─┬ paper-icon-button#1.1.6 (latest is 2.0.1)
│ │ ├─┬ paper-behaviors#1.0.13 (latest is 2.0.1)
│ │ │ ├─┬ iron-behaviors#1.0.18 (latest is 2.0.0)
│ │ │ │ ├─┬ iron-a11y-keys-behavior#1.1.9 (latest is 2.0.1)
│ │ │ ├─┬ iron-checked-element-behavior#1.0.6 (latest is 2.0.0)
│ │ │ │ ├─┬ iron-form-element-behavior#1.0.7 (latest is 2.0.0)
│ │ │ ├─┬ paper-ripple#1.0.10 (latest is 2.0.1)
│ │ │ │ ├── iron-a11y-keys-behavior#1.1.9 (latest is 2.0.1)
│ │ ├─┬ paper-styles#1.3.1 (latest is 2.0.0)
│ │ │ ├── iron-flex-layout#1.3.7 (latest is 2.0.0)
│ ├─┬ iron-a11y-keys#1.0.9 (latest is 2.0.0)
│ ├── iron-behaviors#1.0.18 (latest is 2.0.0)
│ ├── iron-icon#1.0.13 (latest is 2.0.1)
│ ├── iron-icons#2.0.1 incompatible with ^1.1.3 (1.2.1 available, latest is 2.0.1)
│ ├── iron-validatable-behavior#1.1.2 (latest is 2.0.0)
│ ├─┬ paper-badge#1.1.4 (latest is 2.0.0)
│ │ ├── iron-resizable-behavior#1.0.6 (latest is 2.0.1)
│ ├─┬ paper-dropdown-menu#1.5.1 (latest is 2.0.0)
│ │ ├── paper-input#1.1.24 (latest is 2.0.2)
│ │ ├─┬ paper-menu-button#1.5.2 (latest is 2.0.0)
│ │ │ ├─┬ iron-dropdown#1.5.6 (latest is 2.0.0)
│ │ │ │ ├── iron-behaviors#1.0.18 (latest is 2.0.0)
│ │ │ │ ├─┬ iron-overlay-behavior#1.10.4 (latest is 2.1.0)
│ │ │ │ │ ├─┬ iron-fit-behavior#1.2.7 (latest is 2.0.1)
│ │ │ │ ├── iron-resizable-behavior#1.0.6 (latest is 2.0.1)
│ │ │ ├── iron-fit-behavior#1.2.7 (latest is 2.0.1)
│ │ │ ├─┬ neon-animation#1.2.5 (latest is 2.0.1)
│ ├── paper-icon-button#1.1.6 (latest is 2.0.1)
│ ├── paper-input#1.1.24 (latest is 2.0.2)
│ ├── paper-item#2.0.0 incompatible with ^1.2.1 (1.2.2 available, latest is 2.0.0)
│ │ ├─┬ iron-collapse#1.3.0 (latest is 2.0.0)
│ │ ├── iron-menu-behavior#1.3.1 (latest is 2.0.1)
└─┬ vaadin-combo-box#1.3.3 incompatible with ^2.0.0 (2.0.0 available, latest is 3.0.0)
  ├── iron-a11y-announcer#1.0.6 (latest is 2.0.0)
  ├── iron-a11y-keys-behavior#1.1.9 (latest is 2.0.1)
  ├── iron-flex-layout#1.3.7 (latest is 2.0.0)
  ├─┬ iron-form#1.1.6 (latest is 2.0.1)
  │ ├─┬ iron-ajax#1.4.4 (latest is 2.0.5)
  │ │ └─┬ promise-polyfill#1.0.1 (latest is 2.0.1)
  ├── iron-form-element-behavior#1.0.7 (latest is 2.0.0)
  ├── iron-icon#1.0.13 (latest is 2.0.1)
  ├── iron-iconset-svg#1.1.2 (latest is 2.1.0)
  ├── iron-input#1.0.11 (latest is 2.0.1)
  ├─┬ iron-list#1.4.6 (latest is 2.0.10)
  │ ├─┬ iron-scroll-target-behavior#1.1.1 (latest is 2.0.0)
  ├── iron-resizable-behavior#1.0.6 (latest is 2.0.1)
  ├─┬ paper-button#1.0.15 (latest is 2.0.0)
  │ ├─┬ paper-material#1.0.7 (latest is 2.0.0)
  │ │ ├── paper-styles#1.3.1 (latest is 2.0.0)
  ├── paper-icon-button#1.1.6 (latest is 2.0.1)
  ├─┬ paper-input#1.1.24 (latest is 2.0.2)
  │ ├─┬ iron-autogrow-textarea#1.0.15 (latest is 2.1.0)
  │ ├── iron-input#1.0.11 (latest is 2.0.1)
  │ ├── paper-styles#1.3.1 (latest is 2.0.0)
  ├── paper-styles#1.3.1 (latest is 2.0.0)
```

Furthermore, I cannot do a clean `bower install` without extending the `resolutions` section in `bower.json` to:

```
"resolutions": {
    "paper-item": "^2.0.0",
    "iron-icons": "^2.0.1",
    "iron-flex-layout": "^2.0.0",
    "paper-icon-button": "^2.0.0",
    "paper-styles": "^2.0.0",
    "iron-collapse": "^2.0.0",
    "iron-input": "^2.0.1",
    "iron-iconset-svg": "^2.1.0",
    "iron-icon": "^2.0.1",
    "iron-resizable-behavior": "^2.0.1",
    "paper-input": "^2.0.2",
    "iron-a11y-announcer": "^2.0.0",
    "iron-validatable-behavior": "^2.0.0",
    "iron-a11y-keys-behavior": "^2.0.1",
    "iron-form-element-behavior": "^2.0.0"
  }
```

**Comment by Mihaiii** [comment]
I had a talk with @habib535 this morning and told him that I'll try to implement the same solution that is in People app so we won't have to use a custom element for tags, only for combobox.

**Comment by Mihaiii** [comment]
@habib535 Please review.
Also please note that the hybrid version of `paper-search-input` has completely different CSS than the old version. I tried to make it look like it was before - but please check that too.

**Comment by Mihaiii** [comment]
Thanks! In the meantime a new release of `paper-search-input` was made so I updated it again.
Merging.

**Pull request merged**
